#!/bin/sh

ourdir=$(cd $(dirname "${0}") && pwd)

if [ -f config.status ]; then
	make maintainer-clean
fi

(cd "${ourdir}" && ./bootstrap) && \
    "${ourdir}/configure" --enable-maintainer-mode \
		--enable-debug \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--localstatedir=/var \
		--sysconfdir=/etc \
		--with-firewall=nftables \
		--disable-datafiles \
		--enable-openconnect=builtin \
		--enable-openvpn=builtin \
		--enable-vpnc=builtin \
		--enable-session-policy-local=builtin \
		--enable-nmcompat \
		--enable-polkit $* \
		--enable-test
